#### 4. Exercise
Create a function which computes the Euclidean norm of each line for a 2D array.

Use numpy operations and vectorization, avoid for cycles.

In [5]:
import numpy as np

In [6]:
# Here is the wrong solution:
def rowwise_norm(X):
    
    def my_dot(x, y):
        result = 0.0
        for i in range(len(x)):
            result += x[i] * y[i]
        return result

    return np.array([np.sqrt(my_dot(x, x)) for x in X])

In [7]:
X = np.arange(5)[:, None]*np.ones((5, 3));

print(rowwise_norm(X))

print(rowwise_norm([[1], [-1], [1], [-1]]))

[0.         1.73205081 3.46410162 5.19615242 6.92820323]
[1. 1. 1. 1.]


##### The solution

In [11]:
def rowwise_norm_solution(X):
    # The function gets a 2D array.
    
    # Calculating the square of each element of the array.
    square_each_element = np.square(X)
    
    # Calculating the sum of the elements of the array in each line.
    sum_columns = np.sum(square_each_element, axis=1)
    
    # Calculating the square root of each element of the array.
    sqrt_array = np.sqrt(sum_columns)
    
    return sqrt_array

In [12]:
rowwise_norm_solution(X)

array([0.        , 1.73205081, 3.46410162, 5.19615242, 6.92820323])

In [13]:
rowwise_norm_solution([[1], [-1], [1], [-1]])

array([1., 1., 1., 1.])